-- Auto-generated by tools/merge_suite_recipes.py
-- Merges 'Suite de la recette précédente' rows into their predecessor.
-- Idempotent against re-running: if the suite row is gone, the DELETE
-- is a no-op; if its steps were already appended, the UPDATE merges
-- duplicate steps. Inspect the output and only re-run if needed.

begin;

-- ── id=348  →  id=347 ─────────────────────────────
--    prev:  Soupe Kielbasa avec haricots
--    suite: Suite de la recette précédente (Soupe Kielbasa)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Réduire cuisson 10 mn.", "Retirer la saucisse dans le poêle.", "Ajouter le lait.", "Garnir de cèleri.", "Servir.", "Pour servir, 10 mn avec persil, mijoter sans crever.", "Tout d''un coup, fromage râpé fondu.", "Cuire 10 mn — Garnir de persil et soya."]'::jsonb
   )
   where id = 347;

delete from public.recipes where id = 348;

-- ── id=407  →  id=406 ─────────────────────────────
--    prev:  Suite de la recette précédente / Velouté de tomate
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Réserver le mélange au frais 30 min.", "Battre 2 jaunes avec un peu de potage chaud, au moment de servir, ajouter graduellement le potage chaud."]'::jsonb
   )
   where id = 406;

delete from public.recipes where id = 407;

-- ── id=410  →  id=409 ─────────────────────────────
--    prev:  Potage aux légumes de la Bergère
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["1 + 1/2 T bouillon de poulet — Compléter avec une boîte de tomates.", "Mettre dans le bouillon de poulet, ajouter une cuillère à thé de tomate, ajouter à la fin pour épaissir.", "Saupoudrer du fromage parmesan râpé."]'::jsonb
   )
   where id = 409;

delete from public.recipes where id = 410;

-- ── id=415  →  id=414 ─────────────────────────────
--    prev:  Soupe à l'Orge et bœuf
--    suite: Suite de la recette précédente — Soupe à l'Orge et bœuf
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Saupoudrer et cuire en remuant 5 min.", "Ajouter bœuf haché, cuire 5 min puis le bouillon de bœuf.", "Ajouter le navet, le céleri, l''oignon, sel, poivre.", "Réduire le feu — Mijoter 1 heure jusqu''à orge cuite et la pâte tendre."]'::jsonb
   )
   where id = 414;

delete from public.recipes where id = 415;

-- ── id=418  →  id=417 ─────────────────────────────
--    prev:  Soupe de crevettes — poulet
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Ajouter bouillon de poulet ou 1 boîte de bouillon (concentré).", "Ajouter tomates, légumes, sel, poivre — Mijoter 10 à 15 min.", "Ajouter pâte longue cuisson 10 min ou pâte fine: ajouter avec coquilles dans préparation bouillie. Parfumer la soupe."]'::jsonb
   )
   where id = 417;

delete from public.recipes where id = 418;

-- ── id=426  →  id=425 ─────────────────────────────
--    prev:  Crème de carottes
--    suite: Suite de la recette précédente — Crème de carottes
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Chauffer l''huile — Faire revenir l''oignon, ajouter les légumes — bouillon, sel/poivre.", "Ébullition — 10 min puis baisser le feu — Cuire et laisser mijoter 20 min jusqu''à ce que les carottes ramollissent, ajouter la crème — Servir."]'::jsonb
   )
   where id = 425;

delete from public.recipes where id = 426;

-- ── id=431  →  id=430 ─────────────────────────────
--    prev:  Soupe paysanne de Bélinde
--    suite: Suite de la recette précédente — Soupe paysanne de Bélinde
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Conservation : sel — Persil ajouter ou poudre coriandre."]'::jsonb
   )
   where id = 430;

delete from public.recipes where id = 431;

-- ── id=434  →  id=433 ─────────────────────────────
--    prev:  Soupe légumes — Poulet — Ravioli mini
--    suite: Suite de la recette précédente — Soupe légumes Poulet Raviol
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Mijoter à couvert 10 min — bien centrer si sel mauvaise.", "Ajouter jus de citron 18 minutes.", "Garnir et on peut ajouter à la dernière minute pour une belle couleur de Vert."]'::jsonb
   )
   where id = 433;

delete from public.recipes where id = 434;

-- ── id=439  →  id=438 ─────────────────────────────
--    prev:  Soupe Lentille Verte
--    suite: Suite de la recette précédente — Soupe Lentille Verte
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Ajouter herbes — Mouiller avec 1 litre d''eau — Ajouter bouillon les lentilles — Ajouter le tomate.", "Cuisson 1 heure environ — Cuire en faite ébullit, suivi du fini — Blender 1 min jusqu''à crémeux.", "Mijoter jusqu''à consistance désirée.", "Filet de citron à la fin."]'::jsonb
   )
   where id = 438;

delete from public.recipes where id = 439;

-- ── id=444  →  id=443 ─────────────────────────────
--    prev:  Bouillon de Dinde ou de poulet à la Manesse
--    suite: Suite de la recette précédente — Bouillon de Dinde
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Filtrer le bouillon avec passoire.", "Mijoter à feu doux jusqu''à bouillon réduit.", "Verser dans des pots pour usage futur.", "Le couvre de cuisson figés sur le dessus.", "Conservation : 3-4 jours au frigo, 6 mois congelé."]'::jsonb
   )
   where id = 443;

delete from public.recipes where id = 444;

-- ── id=451  →  id=450 ─────────────────────────────
--    prev:  Bonne Soupe de Grand-Mère de St-Pradine
--    suite: Suite de la recette précédente — Bonne Soupe de Grand-Mère
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Ajouter eau, l''avoine, sel, poivre.", "Ajouter pâtes alimentaires.", "Faire mijoter pour 30 min — voilà 20 min."]'::jsonb
   )
   where id = 450;

delete from public.recipes where id = 451;

-- ── id=454  →  id=453 ─────────────────────────────
--    prev:  Soupe de Grand-Maman
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Suite d''une recette précédente avec des croûtons grillés frottés avec de l''ail et des morceaux de fromage de Gruyère, pour un fini plus croustillant."]'::jsonb
   )
   where id = 453;

delete from public.recipes where id = 454;

-- ── id=459  →  id=458 ─────────────────────────────
--    prev:  Bisque de fruits de mer aux trois castelles (Homard?)
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Cuire 5-7 minutes. Au lieu de glace, on peut prendre la crevette rosée. Servir avec du persil."]'::jsonb
   )
   where id = 458;

delete from public.recipes where id = 459;

-- ── id=471  →  id=470 ─────────────────────────────
--    prev:  Potage de concombre à l'aneth (délicieux)
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Dans une casserole, mettre la bouille, faire cuire le bouillon, lait chaud.", "Faire le roux avec une beurre et farine, et le bouillon pour lier.", "Bien laisser pour rester bien généreuse, comme une sauce blanche.", "Cuire 5 minutes à feu doux.", "Ajouter les assaisonnements.", "Garnir d''une pincée de cerfeuil ou pour varier échalote en morceaux les concombres frais.", "Servir chaud ou froid.", "Pour réveiller saupoudrer de sel de mer ou moulin."]'::jsonb
   )
   where id = 470;

delete from public.recipes where id = 471;

-- ── id=535  →  id=534 ─────────────────────────────
--    prev:  Crème de parmesan — Saucisses et Diable (Italienne)?
--    suite: Suite de la recette précédente (parmesan)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Et parmesan râpé — ajouter sur la table", "Ajouter les épinards — sel, poivre", "Garnir chaque bol de fromage."]'::jsonb
   )
   where id = 534;

delete from public.recipes where id = 535;

-- ── id=540  →  id=539 ─────────────────────────────
--    prev:  Soupe — Mini boulettes de porc, pâte parmesan (4 à 6 personn
--    suite: Suite de la recette précédente (mini boulettes/soupe)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Pour la soupe — chauffer le bouillon", "Verser dans la casserole 8 à 10 min — ajouter", "Bouillon et de légumes — ébullition", "Puis réduire à feu doux — ajouter boulettes", "Mijoter 12 min — Mettre les rotis avant que les tomates en dés et autres soient prêtes", "Ne pas trop bouillir, les boulettes seraient prises tendres", "Ajouter le bouillon — légumes (céleri, branches), poireau, sel", "Jusqu''à ce qu''on tienne — la pâte — Rincer", "Ajouter à la soupe"]'::jsonb
   )
   where id = 539;

delete from public.recipes where id = 540;

-- ── id=546  →  id=545 ─────────────────────────────
--    prev:  Soupe de chou-fleur à l'indienne
--    suite: Suite de la recette précédente (chou-fleur indienne)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Revenir les oignons dans l''huile", "Ajouter ensuite le chou-fleur, les patates, gingembre, épices (cumin, coriandre, curcuma, goutte de Tabasco), sel", "Verser 70 cl d''eau", "Ébullition — couvrir — mijoter feu doux 30 min", "Blender", "Incorporer la crème fraîche", "Réchauffer sans bouillir", "Servir"]'::jsonb
   )
   where id = 545;

delete from public.recipes where id = 546;

-- ── id=548  →  id=547 ─────────────────────────────
--    prev:  Crème de chou-fleur au fromage
--    suite: Suite de la recette précédente (crème chou-fleur au fromage)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Laisser mijoter 30 min — Ne pas bouillir"]'::jsonb
   )
   where id = 547;

delete from public.recipes where id = 548;

-- ── id=551  →  id=550 ─────────────────────────────
--    prev:  Chou-fleur — carotte — oignon — fromage fort en potage
--    suite: Suite de la recette précédente (chou-fleur-carotte-fromage f
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Couper les légumes en gros morceaux", "Revenir oignon dans l''huile et le beurre", "Ajouter carottes — chou-fleur revenir dans l''oignon — sel, poivre", "Cuire 2 à 3 min — découvrir, brasser", "Ajouter l''ail — bouillon, eau — persil", "Mijoter 1 h — Le chou-fleur va être en compote", "Si trop liquide, faire réduire un peu plus longtemps", "Blender", "Ajouter le fromage jusqu''à homogène — sel, poivre"]'::jsonb
   )
   where id = 550;

delete from public.recipes where id = 551;

-- ── id=554  →  id=553 ─────────────────────────────
--    prev:  Chaudrée de maïs
--    suite: Suite de la recette précédente (chaudrée de maïs)
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Ajouter 2 T de maïs, curcuma, oignons, sel, poivre", "Mijoter 20 min feu doux", "Blender", "Remettre dans casserole et de nouveau à ébullition", "Ajouter le reste du maïs, carottes et céleri", "Mijoter 8 à 10 min"]'::jsonb
   )
   where id = 553;

delete from public.recipes where id = 554;

-- ── id=561  →  id=560 ─────────────────────────────
--    prev:  Soupe aux poireaux gratinée
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Tranches de pain dans une plaque, griller à chaque côté à broil.", "Répartir la soupe dans bol allant au four.", "Garnir de pain grillé et ajouter fromage râpé.", "3 min à broil."]'::jsonb
   )
   where id = 560;

delete from public.recipes where id = 561;

-- ── id=564  →  id=563 ─────────────────────────────
--    prev:  Crème de Tomate et Orge
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Ajouter les tomates, pâte de tomate, bouillon, sel, poivre.", "Couvrir, cuire 20 à 25 min. Blender.", "Chaudron : Ajouter l''orge, cuire 30 min."]'::jsonb
   )
   where id = 563;

delete from public.recipes where id = 564;

-- ── id=574  →  id=573 ─────────────────────────────
--    prev:  Crème de légumes
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Revenir légumes dans beurre 5 min.", "Ajouter bouillon, ébullition. Mijoter 30 min.", "Blender. Ajouter crème, brasser, réchauffer."]'::jsonb
   )
   where id = 573;

delete from public.recipes where id = 574;

-- ── id=582  →  id=581 ─────────────────────────────
--    prev:  Soupe Express aux légumes
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Émincer finement oignon et ail.", "Couper en petits dés patates.", "Carottes : trancher finement ou couper en petits cubes (plus fins, plus vite cuites).", "Inutile d''éplucher courgette si bio. Couper en rondelles épaisses ou non.", "Revenir oignon et ail, chauffer 1 cà soupe huile olive. Ajouter oignon 2 min, ajouter ail 30 sec.", "Ajouter le reste : patates, carottes, courgette. Verser le liquide, assaisonner. Ébullition, cuire 15 min.", "Mixer ou non au goût.", "Option mixée soupe Velouté et crème : mixer au blender, ajouter 1 cà soupe de crème ou du fromage râpé avant de mixer.", "Soupe rustique : laisser morceaux de légumes intacts.", "Si vous mixez ajouter une touche d''huile olive ou un filet de jus de citron pour réveiller les saveurs.", "Goûter, ajouter sel, poivre, fines herbes fraîches : persil, ciboulette. Mes herbes salées. Huile olive ou beurre.", "Servir avec pain grillé ou ajouter des croûtons maison.", "Ajouter graines de sésame sur le dessus ou parmesan râpé fin."]'::jsonb
   )
   where id = 581;

delete from public.recipes where id = 582;

-- ── id=588  →  id=587 ─────────────────────────────
--    prev:  Soupe de Fork and Fork
--    suite: Suite de la recette précédente
update public.recipes
   set data = jsonb_set(
     data,
     '{steps}',
     coalesce(data->'steps', '[]'::jsonb) || '["Cuire saucisse 5 min dans l''huile.", "Ajouter oignon, céleri, ail, cuire jusqu''à coloration, ajouter sel.", "Ajouter pâte de tomate, conserve, épinards, haricots.", "Déglacer avec eau, bouillon, ajouter tomates.", "Couvrir, laisser mijoter, ajouter pâtes longues, cuire jusqu''à al dente.", "Ajouter bouquets de brocoli (?) et brocolis cuire 5 min.", "À ce stade, ajouter pesto.", "Saler, poivrer, garnir de parmesan.", "Se congèle bien, réchauffer au moins 2-3 minutes."]'::jsonb
   )
   where id = 587;

delete from public.recipes where id = 588;

commit;
