"""Merge "Suite de la recette précédente" recipes into their predecessor.

Background: a long recipe photographed across multiple HEIC pages was split by
the OCR pipeline into separate JSON entries. The continuation entries have:
  - an empty `ingredients` array
  - a title starting with "Suite de la recette précédente"
  - the rest of the steps that belong to the previous recipe

This script walks recipes.json in array order, finds those entries, and
appends their steps to the previous recipe. Output:

  - db/migrations/0001_merge_suite_recipes.sql   — SQL to run against
    the live Supabase project. Wraps the UPDATE+DELETE pairs in a single
    transaction with one savepoint per merge so a partial failure rolls back
    cleanly.
  - assets/categories.json (in place)            — drops the deleted ids
    from each category's recipeIds list.
  - recipes.json (in place)                       — applies the merges to
    the static file too, so the local repo and DB stay in sync after the
    user runs the SQL.

Usage:
  python tools/merge_suite_recipes.py            # DRY RUN — prints plan
  python tools/merge_suite_recipes.py --apply    # actually writes files
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path("C:/Users/JonathanPrince/.claude/projects/BOOK/new-app")
RECIPES   = ROOT / "recipes.json"
CATEGORIES = ROOT / "categories.json"
MIGRATION = ROOT / "db/migrations/0001_merge_suite_recipes.sql"

SUITE_NEEDLE = "suite de la recette"   # case-insensitive substring


def is_suite_continuation(r: dict) -> bool:
    title = (r.get("title") or "").lower()
    ingredients = r.get("ingredients") or []
    return (not ingredients) and (SUITE_NEEDLE in title)


def find_merges(recipes: list[dict]) -> list[dict]:
    """Return one merge plan per "Suite" entry.

    Each plan has: prev_idx, prev_id, suite_idx, suite_id, prev_title,
    suite_title, steps_to_append, prev_step_count.
    """
    plans = []
    for i, r in enumerate(recipes):
        if not is_suite_continuation(r):
            continue
        if i == 0:
            print(f"  WARN: arr_idx={i} (id={r.get('id')}) has no previous — cannot merge", file=sys.stderr)
            continue
        prev = recipes[i - 1]
        plans.append({
            "prev_idx":          i - 1,
            "prev_id":           prev.get("id"),
            "prev_title":        prev.get("title", ""),
            "prev_step_count":   len(prev.get("steps") or []),
            "suite_idx":         i,
            "suite_id":          r.get("id"),
            "suite_title":       r.get("title", ""),
            "steps_to_append":   r.get("steps") or [],
            "suite_notes":       r.get("notes"),
        })
    return plans


def render_dry_run(plans: list[dict]) -> None:
    print(f"=== Plan: {len(plans)} merges ===\n")
    for p in plans:
        print(f"  Merge id={p['suite_id']} → id={p['prev_id']}")
        print(f"    prev:  {p['prev_title'][:60]!r}  ({p['prev_step_count']} existing steps)")
        print(f"    suite: {p['suite_title'][:60]!r}")
        print(f"    appending {len(p['steps_to_append'])} step(s):")
        for s in p["steps_to_append"][:2]:
            print(f"      + {s[:90]!r}")
        if len(p["steps_to_append"]) > 2:
            print(f"      + … +{len(p['steps_to_append']) - 2} more")
        print()
    print(f"After merge: {len(plans)} recipe rows deleted from the DB and from recipes.json.")


def sql_string(s: str) -> str:
    """Escape a Python string for inclusion as a Postgres single-quoted literal."""
    return "'" + s.replace("'", "''") + "'"


def render_sql(plans: list[dict]) -> str:
    """Build a single SQL transaction that applies all merges to the DB."""
    lines = [
        "-- Auto-generated by tools/merge_suite_recipes.py",
        "-- Merges 'Suite de la recette précédente' rows into their predecessor.",
        "-- Idempotent against re-running: if the suite row is gone, the DELETE",
        "-- is a no-op; if its steps were already appended, the UPDATE merges",
        "-- duplicate steps. Inspect the output and only re-run if needed.",
        "",
        "begin;",
        "",
    ]
    for p in plans:
        steps_json = json.dumps(p["steps_to_append"], ensure_ascii=False)
        lines.extend([
            f"-- ── id={p['suite_id']}  →  id={p['prev_id']} ─────────────────────────────",
            f"--    prev:  {p['prev_title'][:60]}",
            f"--    suite: {p['suite_title'][:60]}",
            f"update public.recipes",
            f"   set data = jsonb_set(",
            f"     data,",
            f"     '{{steps}}',",
            f"     coalesce(data->'steps', '[]'::jsonb) || {sql_string(steps_json)}::jsonb",
            f"   )",
            f"   where id = {p['prev_id']};",
            f"",
            f"delete from public.recipes where id = {p['suite_id']};",
            f"",
        ])
    lines.append("commit;")
    return "\n".join(lines) + "\n"


def apply_in_memory(recipes: list[dict], plans: list[dict]) -> list[dict]:
    """Build the merged recipes array (without mutating the input)."""
    # Map id → updated recipe (for UPDATE rows)
    by_id = {r["id"]: dict(r) for r in recipes}
    delete_ids = set()
    for p in plans:
        prev = by_id[p["prev_id"]]
        prev["steps"] = (prev.get("steps") or []) + p["steps_to_append"]
        delete_ids.add(p["suite_id"])
    # Preserve original order, drop deleted
    return [by_id[r["id"]] for r in recipes if r["id"] not in delete_ids]


def update_categories(plans: list[dict]) -> tuple[list[dict], int]:
    """Read categories.json, remove deleted ids from each category's
    recipeIds, and return (new_categories, total_removed)."""
    with open(CATEGORIES, encoding="utf-8") as f:
        cats = json.load(f)
    deleted = {p["suite_id"] for p in plans}
    removed = 0
    for c in cats:
        before = c.get("recipeIds") or []
        after = [rid for rid in before if rid not in deleted]
        c["recipeIds"] = after
        removed += len(before) - len(after)
    return cats, removed


def main() -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true",
                    help="Write the SQL migration + update recipes.json + categories.json. Without this flag the script only prints the plan.")
    args = ap.parse_args()

    print(f"Loading {RECIPES}")
    with open(RECIPES, encoding="utf-8") as f:
        recipes = json.load(f)
    print(f"  {len(recipes)} recipes\n")

    plans = find_merges(recipes)
    if not plans:
        print("No 'Suite' recipes to merge. Nothing to do.")
        return 0

    render_dry_run(plans)

    if not args.apply:
        print("\n(dry run only — re-run with --apply to write files)")
        return 0

    # Apply: write SQL, update recipes.json, update categories.json
    MIGRATION.parent.mkdir(parents=True, exist_ok=True)
    with open(MIGRATION, "w", encoding="utf-8", newline="\n") as f:
        f.write(render_sql(plans))
    print(f"\n→ Wrote {MIGRATION.relative_to(ROOT)}  ({len(plans)} merges in 1 transaction)")

    new_recipes = apply_in_memory(recipes, plans)
    with open(RECIPES, "w", encoding="utf-8", newline="\n") as f:
        json.dump(new_recipes, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"→ Wrote {RECIPES.relative_to(ROOT)}  ({len(recipes)} → {len(new_recipes)} recipes)")

    new_cats, removed = update_categories(plans)
    with open(CATEGORIES, "w", encoding="utf-8", newline="\n") as f:
        json.dump(new_cats, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"→ Wrote {CATEGORIES.relative_to(ROOT)}  (removed {removed} recipe references)")

    print("\nNext steps:")
    print(f"  1. Open {MIGRATION.relative_to(ROOT)} → paste into Supabase SQL Editor → Run")
    print(f"  2. Commit recipes.json + categories.json + the migration file")
    print(f"  3. (Optional) Click Publier on the dashboard — DB and recipes.json will already match,")
    print(f"     so the function will short-circuit with 'Aucun changement'.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
